from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field

class Severity(str, Enum):
    """Severity level of an event or alert."""

    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"

class AlertStatus(str, Enum):
    """Current status of an alert."""

    ACTIVE = "ACTIVE"
    RESOLVED = "RESOLVED"

class Alert(BaseModel):
    """Represents an active alert generated by the system."""

    id: int = Field(
        ...,
        description="Unique alert identifier",
        examples=[1],
    )

    camera_id: str = Field(
        ...,
        description="Camera that generated the alert",
        examples=["CAM-001"],
    )

    event_type: str = Field(
        ...,
        description="Type of detected event",
        examples=["VIRTUAL_FENCE_BREACH"],
    )

    severity: Severity = Field(
        ...,
        description="Severity level of the alert",
        examples=[Severity.HIGH],
    )

    status: AlertStatus = Field(
        default=AlertStatus.ACTIVE,
        description="Current status of the alert",
    )

    timestamp: datetime = Field(
        ...,
        description="Time when the alert was generated",
    )

    confidence: Optional[float] = Field(
        default=0.92,
        ge=0.0,
        le=1.0,
        description="Confidence score of the alert detection",
        examples=[0.92],
    )

    details: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Forensic context and detection details",
    )

class CreateAlertRequest(BaseModel):
    """Request payload to create a new alert."""

    camera_id: str = Field(
        ...,
        description="Camera that generated the alert",
        examples=["CAM-001"],
    )

    event_type: str = Field(
        ...,
        description="Type of detected event",
        examples=["VIRTUAL_FENCE_BREACH"],
    )

    severity: Severity = Field(
        ...,
        description="Severity level of the alert",
        examples=[Severity.HIGH],
    )

    status: Optional[AlertStatus] = Field(
        default=AlertStatus.ACTIVE,
        description="Initial status of the alert",
    )

    confidence: Optional[float] = Field(
        default=0.92,
        ge=0.0,
        le=1.0,
        description="Detection confidence score",
        examples=[0.92],
    )

    timestamp: Optional[datetime] = Field(
        default=None,
        description="Timestamp of the alert",
    )

    details: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Optional forensic context and detection details",
    )

class AlertListResponse(BaseModel):
    """Response containing all active and resolved alerts."""

    total: int = Field(
        ...,
        description="Total number of alerts",
        examples=[2],
    )

    alerts: List[Alert] = Field(
        ...,
        description="List of alerts",
    )