from datetime import datetime
from enum import Enum
from pydantic import BaseModel, Field
from typing import List

class Severity(str, Enum):
    """Severity level of an event or alert."""

    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"

class AlertStatus(str, Enum):
    """Current status of an alert."""

    ACTIVE = "ACTIVE"
    RESOLVED = "RESOLVED"

class Alert(BaseModel):
    """Represents an active alert generated by the system."""

    id: int = Field(
        ...,
        description="Unique alert identifier",
        examples=[1],
    )

    camera_id: str = Field(
        ...,
        description="Camera that generated the alert",
        examples=["CAM_001"],
    )

    event_type: str = Field(
        ...,
        description="Type of detected event",
        examples=["Virtual Fence Breach"],
    )

    severity: Severity = Field(
        ...,
        description="Severity level of the alert",
        examples=[Severity.HIGH],
    )

    status: AlertStatus = Field(
        default=AlertStatus.ACTIVE,
        description="Current status of the alert",
    )

    timestamp: datetime = Field(
        ...,
        description="Time when the alert was generated",
    )

class CreateAlertRequest(BaseModel):
    """Request payload to create a new alert."""

    camera_id: str = Field(
        ...,
        description="Camera that generated the alert",
        examples=["CAM_001"],
    )

    event_type: str = Field(
        ...,
        description="Type of detected event",
        examples=["Virtual Fence Breach"],
    )

    severity: Severity = Field(
        ...,
        description="Severity level of the alert",
        examples=[Severity.HIGH],
    )

class AlertListResponse(BaseModel):
    """Response containing all active and resolved alerts."""

    total: int = Field(
        ...,
        description="Total number of alerts",
        examples=[2],
    )

    alerts: List[Alert] = Field(
        ...,
        description="List of alerts",
    )